version: ~> 1.0
language: c
os: linux
dist: bionic


_gcc_7: &_gcc_7
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-7

_gcc_8: &_gcc_8
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-8

_gcc_9: &_gcc_9
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-9

_gcc_10: &_gcc_10
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-10

_clang_9: &_clang_9
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        # Work around Travis' documenation not matching the whitelist
        # - llvm-toolchain-bionic-9
        - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      packages:
        - clang-9
        - lld-9
        - llvm-9-dev

_clang_10: &_clang_10
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        # Work around Travis' documenation not matching the whitelist
        # - llvm-toolchain-bionic-10
        - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      packages:
        - clang-10
        - lld-10
        - llvm-10-dev

_clang_11: &_clang_11
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        # Work around Travis' documenation not matching the whitelist
        # - llvm-toolchain-bionic
        - sourceline: 'deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial main'
          key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      packages:
        - clang-11
        - lld-11
        - llvm-11-dev

jobs:
  include:
    # GCC 7 tests
    - name: GCC 7, 64bit
      <<: *_gcc_7
      env: CC=gcc-7 BITS32=n LTO=n
    - name: GCC 7, 64bit LTO
      <<: *_gcc_7
      env: CC=gcc-7 BITS32=n LTO=y
    - name: GCC 7, 32bit
      <<: *_gcc_7
      env: CC=gcc-7 BITS32=y LTO=n
    - name: GCC 7, 32bit LTO
      <<: *_gcc_7
      env: CC=gcc-7 BITS32=y LTO=y

    # GCC 8 tests
    - name: GCC 8, 64bit
      <<: *_gcc_8
      env: CC=gcc-8 BITS32=n LTO=n
    - name: GCC 8, 64bit LTO
      <<: *_gcc_8
      env: CC=gcc-8 BITS32=n LTO=y
    - name: GCC 8, 32bit
      <<: *_gcc_8
      env: CC=gcc-8 BITS32=y LTO=n
    - name: GCC 8, 32bit LTO
      <<: *_gcc_8
      env: CC=gcc-8 BITS32=y LTO=y

    # GCC 9 tests
    - name: GCC 9, 64bit
      <<: *_gcc_9
      env: CC=gcc-9 BITS32=n LTO=n
    - name: GCC 9, 64bit LTO
      <<: *_gcc_9
      env: CC=gcc-9 BITS32=n LTO=y
    - name: GCC 9, 32bit
      <<: *_gcc_9
      env: CC=gcc-9 BITS32=y LTO=n
    - name: GCC 9, 32bit LTO
      <<: *_gcc_9
      env: CC=gcc-9 BITS32=y LTO=y

    # GCC 10 tests
    - name: GCC 10, 64bit
      <<: *_gcc_10
      env: CC=gcc-10 BITS32=n LTO=n
    - name: GCC 10, 64bit LTO
      <<: *_gcc_10
      env: CC=gcc-10 BITS32=n LTO=y
    - name: GCC 10, 32bit
      <<: *_gcc_10
      env: CC=gcc-10 BITS32=y LTO=n
    - name: GCC 10, 32bit LTO
      <<: *_gcc_10
      env: CC=gcc-10 BITS32=y LTO=y

    # Clang 9 tests
    - name: Clang 9, 64bit
      <<: *_clang_9
      env: CC=clang-9 BITS32=n LTO=n
    - name: Clang 9, 64bit LTO
      <<: *_clang_9
      env: CC=clang-9 BITS32=n LTO=y
    - name: Clang 9, 32bit
      <<: *_clang_9
      env: CC=clang-9 BITS32=y LTO=n
    - name: Clang 9, 32bit LTO
      <<: *_clang_9
      env: CC=clang-9 BITS32=y LTO=y

    # Clang 10 tests
    - name: Clang 10, 64bit
      <<: *_clang_10
      env: CC=clang-10 BITS32=n LTO=n
    - name: Clang 10, 64bit LTO
      <<: *_clang_10
      env: CC=clang-10 BITS32=n LTO=y
    - name: Clang 10, 32bit
      <<: *_clang_10
      env: CC=clang-10 BITS32=y LTO=n
    - name: Clang 10, 32bit LTO
      <<: *_clang_10
      env: CC=clang-10 BITS32=y LTO=y

    # Clang 11 tests
    - name: Clang 11, 64bit
      <<: *_clang_11
      env: CC=clang-11 BITS32=n LTO=n
    - name: Clang 11, 64bit LTO
      <<: *_clang_11
      env: CC=clang-11 BITS32=n LTO=y
    - name: Clang 11, 32bit
      <<: *_clang_11
      env: CC=clang-11 BITS32=y LTO=n
    - name: Clang 11, 32bit LTO
      <<: *_clang_11
      env: CC=clang-11 BITS32=y LTO=y

script:
  - make 32=$BITS32
  - ./extend_lz_only.sh
